# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {G:/My Drive/Alchitry/UCD-P118-blank/work/vivado/UCD-P118-blank/UCD-P118-blank.cache/wt} [current_project]
set_property parent.project_path {G:/My Drive/Alchitry/UCD-P118-blank/work/vivado/UCD-P118-blank/UCD-P118-blank.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{G:/My Drive/Alchitry/UCD-P118-blank/work/vivado/UCD-P118-blank/UCD-P118-blank.srcs/sources_1/imports/verilog/au_top_0.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Program Files/Alchitry/Alchitry Labs/library/components/au.xdc}}
set_property used_in_implementation false [get_files {{C:/Program Files/Alchitry/Alchitry Labs/library/components/au.xdc}}]

read_xdc {{G:/My Drive/Alchitry/UCD-P118-blank/work/constraint/Alchitry-UCD.xdc}}
set_property used_in_implementation false [get_files {{G:/My Drive/Alchitry/UCD-P118-blank/work/constraint/Alchitry-UCD.xdc}}]


synth_design -top au_top_0 -part xc7a35tftg256-1


write_checkpoint -force -noxdef au_top_0.dcp

catch { report_utilization -file au_top_0_utilization_synth.rpt -pb au_top_0_utilization_synth.pb }
