# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/ericp/github/UCD_P118_Alchitry/ADC-FIR-DAC/work/constraint/test.xdc

# XDC: C:/Program Files/Alchitry/Alchitry Labs/library/components/au.xdc

# IP: ip/fir_compiler_0/fir_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] -quiet
